"""Alembic environment for the BeeAtlas authoritative notes store.

Key design choices:
- URL is derived from NOTES_DB_PATH env var (default /opt/beeatlas-store/notes.db)
  — never hard-coded in alembic.ini. Tests override NOTES_DB_PATH to a tmp path.
- render_as_batch=True is REQUIRED for SQLite: SQLite does not support most ALTER
  TABLE operations (drop column, add constraint, change column type). Alembic batch
  mode works around this by recreating the table via INSERT…SELECT.
- target_metadata = Base.metadata connects Alembic's autogenerate to the ORM models.
- Offline mode is intentionally minimal (raises) — this store is only migrated
  online, never via SQL script dump. The online path is the only supported path.
"""

import os
from logging.config import fileConfig

from sqlalchemy import create_engine

from alembic import context

# ---------------------------------------------------------------------------
# Alembic Config object — provides access to .ini values + logging setup
# ---------------------------------------------------------------------------
config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# ---------------------------------------------------------------------------
# Resolve the SQLite database path from NOTES_DB_PATH env var
# ---------------------------------------------------------------------------
NOTES_DB_PATH = os.environ.get("NOTES_DB_PATH", "/opt/beeatlas-store/notes.db")

# ---------------------------------------------------------------------------
# Import the ORM metadata so autogenerate can diff model vs schema
# ---------------------------------------------------------------------------
from notes_store.models import Base  # noqa: E402

target_metadata = Base.metadata


# ---------------------------------------------------------------------------
# Migration runners
# ---------------------------------------------------------------------------


def run_migrations_offline() -> None:
    """Offline mode is not supported for the authoritative store.

    Migrations must run against the live SQLite file (online mode), never via
    a SQL script dump. Raise immediately so the operator knows to use
    ``alembic upgrade head`` against the real DB.
    """
    raise NotImplementedError(
        "Offline migration mode is not supported for the authoritative notes store. "
        "Run `alembic upgrade head` against the live SQLite file (online mode)."
    )


def run_migrations_online() -> None:
    """Online migration: connect to the SQLite file and run all pending migrations.

    render_as_batch=True is the critical SQLite compatibility setting (see module
    docstring). It is set globally here so every migration — including future
    autogenerated ones — uses batch mode automatically.
    """
    connectable = create_engine(
        f"sqlite:///{NOTES_DB_PATH}",
        connect_args={"check_same_thread": False},
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,  # REQUIRED for SQLite ALTER TABLE workarounds
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
